#' Resolve the visual theme for this render
#' @description
#' Priority: CV_THEME env var > config.yaml `theme:` > "warm". Unknown names
#' fall back to "subtle" with a warning (matching the previous behaviour).
#' @return A list: `name`, `colours` (token -> hex) and `fonts`.
load_theme <- function(config, path = file.path("themes", "themes.yml")) {
  spec <- yaml::read_yaml(path)

  name <- Sys.getenv("CV_THEME", unset = "")
  if (name == "") name <- if (!is.null(config$theme)) config$theme else "warm"
  name <- tolower(trimws(name))
  if (!name %in% names(spec$themes)) {
    warning(sprintf("Unknown CV theme '%s'; falling back to 'subtle'.", name))
    name <- "subtle"
  }

  # Palette names resolve to their hex value; literal hex passes through
  colours <- lapply(spec$themes[[name]], function(value) {
    if (!is.null(spec$palette[[value]])) spec$palette[[value]] else value
  })

  list(name = name, colours = colours, palette = spec$palette, fonts = spec$fonts)
}

#' Theme tokens as a raw HTML <style> block (dropped from the Typst output)
#' @description
#' Overrides the --cv-* custom properties that styles/cv.css styles with.
theme_css <- function(theme) {
  declarations <- c(
    sprintf("  --bb-%s: %s;", names(theme$palette), unlist(theme$palette)),
    sprintf("  --cv-%s: %s;", names(theme$colours), unlist(theme$colours))
  )
  paste(
    c(
      "```{=html}",
      sprintf('<style id="cv-theme" data-theme="%s">', theme$name),
      ":root {",
      declarations,
      "}",
      "</style>",
      "```",
      ""
    ),
    collapse = "\n"
  )
}

#' Write the theme as a Typst dictionary imported by the PDF template
#' @description
#' Typst cannot read environment variables, so the selected theme is handed
#' over as a small generated module (git-ignored).
write_theme_typst <- function(theme, path = file.path("typst", "_theme.typ")) {
  colour_entries <- sprintf(
    '  %s: rgb("%s"),',
    names(theme$colours),
    unlist(theme$colours)
  )
  palette_entries <- sprintf(
    '  %s: rgb("%s"),',
    names(theme$palette),
    unlist(theme$palette)
  )
  font_entries <- sprintf('  %s: "%s",', names(theme$fonts), unlist(theme$fonts))

  writeLines(
    c(
      "// Generated by R/theme.R from themes/themes.yml -- do not edit.",
      sprintf('#let cv-theme-name = "%s"', theme$name),
      "#let cv-theme = (",
      colour_entries,
      ")",
      "#let cv-palette = (",
      palette_entries,
      ")",
      "#let cv-fonts = (",
      font_entries,
      ")"
    ),
    path
  )
  invisible(path)
}
